### ISSUE TITLE
[Question]: test `test-fda-table_02.R` not successfully

### ISSUE THREAD

**Issue by ynsec37** [pharmaverse/falcon#179] opened 2023-11-29 10:16 UTC
### What is your question?

After clone the repository, I run the test `test-fda-table_02.R`

Run tests by clink the button

![image](https://github.com/pharmaverse/falcon/assets/98389771/0ba9012e-6531-4198-834b-9f872b100484)

Test output

![image](https://github.com/pharmaverse/falcon/assets/98389771/1d4de936-7cac-46ef-8f05-843cbf370d2f)

I want to confirm if the test is ok for you, or if there are some mistakes on my side.

Thank you very much.

`sessionInfo()`
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scda_0.1.6        dplyr_1.1.4       falcon_0.1.0.9047 testthat_3.2.0    tern_0.9.0       
 [6] rtables_0.6.3     magrittr_2.0.3    formatters_0.5.2  devtools_2.4.5    usethis_2.2.2    

loaded via a namespace (and not attached):
 [1] fs_1.6.3             lubridate_1.9.3      rprojroot_2.0.4      R.cache_0.16.0      
 [5] tools_4.2.2          profvis_0.3.8        backports_1.4.1      utf8_1.2.4          
 [9] R6_2.5.1             colorspace_2.1-0     urlchecker_1.0.1     withr_2.5.2         
[13] tfrmt_0.1.0          tidyselect_1.2.0     prettyunits_1.2.0    processx_3.8.2      
[17] compiler_4.2.2       cli_3.6.1            gt_0.10.0            xml2_1.3.5          
[21] desc_1.4.2           scales_1.3.0         checkmate_2.3.0      readr_2.1.4         
[25] callr_3.7.3          commonmark_1.9.0     stringr_1.5.1        digest_0.6.33       
[29] rmarkdown_2.25       R.utils_2.12.3       pkgconfig_2.0.3      htmltools_0.5.7     
[33] sessioninfo_1.2.2    styler_1.10.2        fastmap_1.1.1        htmlwidgets_1.6.3   
[37] rlang_1.1.2          Tplyr_1.1.0          rstudioapi_0.15.0    shiny_1.8.0         
[41] generics_0.1.3       rlistings_0.2.4      jsonlite_1.8.7       R.oo_1.25.0         
[45] Matrix_1.6-3         Rcpp_1.0.11          waldo_0.5.2          munsell_0.5.0       
[49] fansi_1.0.5          clipr_0.8.0          R.methodsS3_1.8.2    lifecycle_1.0.4     
[53] yaml_2.3.7           stringi_1.8.1        gtsummary_1.7.2      brio_1.1.3          
[57] pkgbuild_1.4.2       grid_4.2.2           promises_1.2.1       forcats_1.0.0       
[61] crayon_1.5.2         miniUI_0.1.1.1       lattice_0.22-5       haven_2.5.3         
[65] splines_4.2.2        hms_1.1.3            knitr_1.45           ps_1.7.5            
[69] pillar_1.9.0         markdown_1.11        pkgload_1.3.3        reprex_2.0.2        
[73] glue_1.6.2           evaluate_0.23        broom.helpers_1.14.0 remotes_2.4.2.1     
[77] vctrs_0.6.4          tzdb_0.4.0           httpuv_1.6.12        Rdpack_2.6          
[81] gtable_0.3.4         purrr_1.0.2          tidyr_1.3.0          assertthat_0.2.1    
[85] cachem_1.0.8         ggplot2_3.4.4        xfun_0.41            mime_0.12           
[89] rbibutils_2.2.16     xtable_1.8-4         broom_1.0.5          later_1.3.1         
[93] survival_3.5-7       tibble_3.2.1         memoise_2.0.1        timechange_0.2.0    
[97] ellipsis_0.3.2      
```

**Comment by edelarua** [comment] 2023-12-01 21:32
Hi @ynsec37,

This is caused by a version mismatch - snapshots were likely generated by developers using `rtables` v0.6.5 or higher and `formatters` v0.5.4 or higher. 

This will be fixed in the next week or two since new versions of these packages will be released on CRAN, but in the meantime you can either ignore these test mismatches or manually update these two packages to the development versions which should fix the tests.

Please let me know if you have any other questions. Thanks!!

**Closed** 2023-12-02 04:29 UTC
Labels: question
